#!/usr/bin/env bash
set -euo pipefail

# Build a sanitized Protomegabot/OmegaClaw disaster-recovery repo snapshot.
# Usage: backup-protomegabot-recovery.sh /path/to/protomegabot-recovery-repo

if [[ $# -ne 1 ]]; then
  echo "usage: $0 /path/to/protomegabot-recovery-repo" >&2
  exit 2
fi

repo="$1"
workspace="/home/openclaw/research-agent"
project="$workspace/projects/omegaclaw"
mkdir -p "$repo"
cd "$workspace"

mkdir -p "$repo/omegaclaw" "$repo/scripts"

cat > "$repo/README.md" <<'EOF'
# Protomegabot Recovery

Private disaster-recovery snapshot for reconstructing Protomegabot / OmegaClaw / ProtomegaTron local context.

This repository intentionally excludes Telegram bot tokens, OpenClaw credentials, provider credentials, model caches, virtualenvs, and cloned upstream repositories. Re-enter credentials manually after restoration.
EOF

cat > "$repo/MANIFEST.md" <<'EOF'
# Manifest

## Included

- OmegaClaw project notebook files: `PROJECT.md`, `TASKS.md`, `DECISIONS.md`, `NOTES.md`, `RUNBOOK.md` when present.
- Non-secret local wrappers/configuration templates under `projects/omegaclaw/local/`, excluding `.env` files and generated logs/state.
- Pointers to upstream repositories and local patch status.
- Backup/restore scripts.

## Excluded

- Telegram bot token and `/home/openclaw/.openclaw/omegaclaw-telegram.env`.
- Any `.env`, provider credentials, SSH keys, OpenClaw credential state.
- `repos/` clones, `.venv`, SWI build trees, HuggingFace/model caches, Chroma DB, logs, attachment downloads, and generated artifacts.
- Raw Telegram/chat/session logs unless separately curated and sanitized.
EOF

cat > "$repo/RESTORE.md" <<'EOF'
# Restore Notes

1. Recreate the OpenClaw research-agent workspace first, ideally from the ZeroBot recovery repo.
2. Recreate `projects/omegaclaw/` notebooks and local non-secret wrappers from this repo.
3. Re-clone upstream repositories listed in `omegaclaw/REPOSITORY_POINTERS.md` instead of restoring bulky local clones.
4. Rebuild SWI/PeTTa/OmegaClaw dependencies according to `omegaclaw/RUNBOOK.md` and current upstream docs.
5. Re-enter Telegram/OpenClaw/provider credentials manually into local secret files; do not source them from this repo.
6. Run mock-mode and private Telegram smoke tests before any long-lived group or provider-backed run.
EOF

# Core notebooks/runbook.
for f in PROJECT.md TASKS.md DECISIONS.md NOTES.md RUNBOOK.md; do
  [[ -f "$project/$f" ]] && cp -p "$project/$f" "$repo/omegaclaw/$f"
done

# Non-secret local operational wrappers/templates. Exclude env/log/state/cache/build-heavy paths.
if [[ -d "$project/local" ]]; then
  rsync -a --delete --delete-excluded \
    --exclude='*.env' --exclude='.env*' --exclude='*.log' --exclude='*.pid' \
    --exclude='__pycache__' --exclude='*.pyc' \
    --exclude='.venv' --exclude='venv' --exclude='*venv*' \
    --exclude='swipl-*' --exclude='huggingface' --exclude='sentence_transformers' \
    "$project/local/" "$repo/omegaclaw/local/"
fi

# Capture lightweight git pointers for local clones without copying clones.
{
  echo '# Repository Pointers'
  echo
  echo 'Generated by backup-protomegabot-recovery.sh. Re-clone these repositories during restore; do not treat this as a full source backup.'
  echo
  find "$project/repos" -maxdepth 4 -type d -name .git 2>/dev/null | sort | while read -r gitdir; do
    worktree="${gitdir%/.git}"
    rel="${worktree#$workspace/}"
    remote=$(git -C "$worktree" remote get-url origin 2>/dev/null || true)
    branch=$(git -C "$worktree" branch --show-current 2>/dev/null || true)
    commit=$(git -C "$worktree" rev-parse HEAD 2>/dev/null || true)
    dirty=$(git -C "$worktree" status --short 2>/dev/null | wc -l | tr -d ' ')
    printf '## `%s`\n\n- remote: `%s`\n- branch: `%s`\n- commit: `%s`\n- dirty-file-count-at-backup: `%s`\n\n' "$rel" "$remote" "$branch" "$commit" "$dirty"
  done
} > "$repo/omegaclaw/REPOSITORY_POINTERS.md"

cp -p projects/agent-recovery/scripts/backup-protomegabot-recovery.sh "$repo/scripts/"

cat > "$repo/.gitignore" <<'EOF'
.env
*.env
*.pem
*.key
id_rsa*
id_ed25519*
.openclaw/
repos/
.venv/
node_modules/
__pycache__/
*.pyc
.DS_Store
*.log
*.pid
EOF

if grep -RInE '(BEGIN (RSA|OPENSSH|EC|DSA) PRIVATE KEY|bot[0-9]{8,}:[A-Za-z0-9_-]{30,}|sk-(proj-)?[A-Za-z0-9]{32,}|gh[pousr]_[A-Za-z0-9_]{20,}|xox[baprs]-[A-Za-z0-9-]{20,})' "$repo" \
  --exclude-dir=.git --exclude='backup-protomegabot-recovery.sh'; then
  echo "Potential secret pattern found; inspect before committing." >&2
  exit 3
fi

echo "Protomegabot recovery snapshot prepared at $repo"
