"""Reference-consistent covariance steering for iterative learning systems."""

from .actuators import (
    DirectTransitionActuator,
    MomentumStepBatchActuator,
    StepBatchActuator,
    StepNoiseActuator,
    StepOnlyActuator,
    TransitionActuator,
)
from .adapters import CallbackAdapter, ChannelAdapter, DynamicsAdapter
from .clocks import FeasibilityClock, LinearWarp, SmootherstepWarp, SmoothstepWarp
from .controller import BridgeController, BridgeEpisode, Channel
from .diagnostics import BridgeTrace, CalibrationReport
from .guards import GuardDecision, PatienceMetricGuard, ProgressGuard
from .observers import (
    AR2AdequacyEstimate,
    AR2AdequacyObserver,
    AttackReleaseFilter,
    CurvatureResponseObserver,
    EmpiricalTransitionObserver,
    ExponentialFilter,
    ResidualDecayObserver,
    SecantCurvatureObserver,
    SplitBatchNoiseObserver,
    block_variances,
)
from .paths import (
    BridgePath,
    ConstantVariancePath,
    GaussianBridgePath,
    LinearGaussianBridgePath,
    PeakQuadraticPath,
)
from .planners import (
    PlannerDecision,
    ReferenceBridgePlanner,
    SharpnessAwareReferenceBridgePlanner,
    TransitionPlanner,
)
from .probing import (
    AntitheticProbePolicy,
    ConfidenceProbePolicy,
    NoProbePolicy,
    ProbeDecision,
    ProbePolicy,
)
from .projectors import GaussianKLProjector, PreserveContractionProjector
from .references import (
    CallbackReferencePolicy,
    FilteredReferencePolicy,
    FixedReferencePolicy,
    ObservedReferencePolicy,
    ReferencePolicy,
)
from .identification import (
    ForgettingFactorAR2Observer,
    GrayBoxMomentumEstimate,
    GrayBoxMomentumObserver,
    RLSAR2Estimate,
    StructuralAR2AdequacyObserver,
    StructuralAdequacyEstimate,
)
from .sharpness import (
    CurvatureAdequacyObserver,
    CurvatureAdequacyReport,
    CurvatureFunnel,
    CurvatureModelLadder,
    DominantSharpnessCoordinator,
    GainScheduledSharpnessModel,
    SharpnessJumpDetector,
    SharpnessJumpReport,
    SharpnessModel,
    SharpnessPlant,
    StaticLinearCurvatureModel,
)
from .stability import (
    CompanionDiagnostics,
    CompanionSmallGainReport,
    companion_matrix,
    companion_small_gain_bound,
    companion_roots,
    covariance_norm,
    damping_regime,
    edge_margin,
    inside_stability_triangle,
    jury_margins,
    lyapunov_metric,
    momentum_coefficients,
    spectral_radius,
    underdamped_contraction_floor,
    verify_common_lyapunov,
)
from .scales import (
    CenteredWidthObserver,
    IQRScale,
    MADScale,
    ScaleEstimator,
    TrimmedVarianceScale,
    VarianceScale,
)
from .types import (
    ActuationPlan,
    ChannelObservation,
    ChannelState,
    ControlCommand,
    GaussianState,
    GaussianTransition,
    LocalDynamics,
)

__version__ = "0.3.0"

__all__ = [
    "AR2AdequacyEstimate",
    "AR2AdequacyObserver",
    "ActuationPlan",
    "AttackReleaseFilter",
    "BridgeController",
    "BridgeEpisode",
    "BridgePath",
    "BridgeTrace",
    "CalibrationReport",
    "CallbackAdapter",
    "CallbackReferencePolicy",
    "CenteredWidthObserver",
    "Channel",
    "ChannelAdapter",
    "ChannelObservation",
    "ChannelState",
    "ConfidenceProbePolicy",
    "ConstantVariancePath",
    "ControlCommand",
    "CurvatureResponseObserver",
    "DirectTransitionActuator",
    "DynamicsAdapter",
    "EmpiricalTransitionObserver",
    "ExponentialFilter",
    "FeasibilityClock",
    "FilteredReferencePolicy",
    "FixedReferencePolicy",
    "GaussianBridgePath",
    "GaussianKLProjector",
    "GaussianState",
    "GaussianTransition",
    "GuardDecision",
    "IQRScale",
    "LinearGaussianBridgePath",
    "LinearWarp",
    "LocalDynamics",
    "MADScale",
    "NoProbePolicy",
    "ObservedReferencePolicy",
    "PatienceMetricGuard",
    "PeakQuadraticPath",
    "PlannerDecision",
    "PreserveContractionProjector",
    "ProbePolicy",
    "ProgressGuard",
    "ReferenceBridgePlanner",
    "ReferencePolicy",
    "ResidualDecayObserver",
    "ScaleEstimator",
    "SecantCurvatureObserver",
    "SmootherstepWarp",
    "SmoothstepWarp",
    "SplitBatchNoiseObserver",
    "StepBatchActuator",
    "StepNoiseActuator",
    "StepOnlyActuator",
    "TransitionActuator",
    "TransitionPlanner",
    "TrimmedVarianceScale",
    "VarianceScale",
    "block_variances",
    "AntitheticProbePolicy",
    "CompanionDiagnostics",
    "CurvatureAdequacyObserver",
    "CurvatureAdequacyReport",
    "CurvatureFunnel",
    "CurvatureModelLadder",
    "DominantSharpnessCoordinator",
    "ForgettingFactorAR2Observer",
    "GainScheduledSharpnessModel",
    "GrayBoxMomentumEstimate",
    "GrayBoxMomentumObserver",
    "MomentumStepBatchActuator",
    "ProbeDecision",
    "RLSAR2Estimate",
    "SharpnessAwareReferenceBridgePlanner",
    "SharpnessJumpDetector",
    "SharpnessJumpReport",
    "SharpnessModel",
    "SharpnessPlant",
    "StaticLinearCurvatureModel",
    "StructuralAR2AdequacyObserver",
    "StructuralAdequacyEstimate",
    "companion_matrix",
    "companion_roots",
    "covariance_norm",
    "damping_regime",
    "edge_margin",
    "inside_stability_triangle",
    "jury_margins",
    "lyapunov_metric",
    "momentum_coefficients",
    "spectral_radius",
    "underdamped_contraction_floor",
    "verify_common_lyapunov",
    "CompanionSmallGainReport",
    "companion_small_gain_bound",
]
